### PR TITLE
update from jquast, add note about Java version

### PR DESCRIPTION
**Pull request by landfillbaby**
see https://github.com/termux/termux-app/pull/1693

### CODE REVIEW

**Comment by landfillbaby** [comment]
wait don't merge yet

**Comment by landfillbaby** [comment]
ignore that force push. oops

**Comment by Grimler91** [comment]
Great, thanks!

**Comment by landfillbaby** [comment]
btw the description should be updated to say it's Unicode 13-conformant

**Comment by Grimler91** [comment]
@landfillbaby thanks again, updated

**Pull request merged**
